### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ghost** [ConnorAtherton/OctoPanel#1]
Hi

I'm getting errors installing OctoPanel, is it normal?

http://pastebin.com/7sBNDx5B

**Comment by ConnorAtherton** [comment]
In your `_config.yml` add this to the end

```
# Gravatar  
gravatar_email: your_gravatar_email
```

Let me know if this fixes it and I'll add it to the README

**Comment by krumjahn** [comment]
I'm getting the same error.

**Comment by ConnorAtherton** [comment]
Check the above comment and the README. You need to add in a `gravatar_email` variable in your `config.yml`. I've opened an issue with the plugin author to try and avoid this. Thanks for being patient guys and please do contribute to the theme if you can!

**Comment by joeljacobson** [comment]
Does not work for me with gravatar details in config.yml

**Comment by ConnorAtherton** [comment]
Hey Joel,

I've updated the `README` and I should have included `gravatar.rb` too. Copy it to your plugins directory and see if that works please. 

I've recreated this error `Liquid Exception: Unknown tag 'gravatar_image' in page` and this fixed it.

**Comment by krumjahn** [comment]
It works!

**Comment by joeljacobson** [comment]
thank you, great theme.

**Comment by robskrob** [comment]
I've created a file called, gravatar.rb, in the plugins directory. What code do I enter there?

**Comment by robskrob** [comment]
Answered my own question. Basically, I just copied and pasted Connor's code from gravatar.rb into my gravatar file. works. Sweet theme, Conor.
