### ISSUE TITLE
Post preview

### ISSUE THREAD

**Issue by aritzportuondo** [ConnorAtherton/OctoPanel#4]
Could you please tell me how can I do to "activate" the visualization of each post preview? Now only titles appears. Thanks and good work!

**Comment by ConnorAtherton** [comment]
Hey man, could you explain this a little more please?

**Comment by aritzportuondo** [comment]
Yes. I installed your skin and now I can see the titles of all of my posts in the main screen. Now, to read the post I have to click on each title but what I want is to be able to see a preview of my posts without clicking on each title.

**Comment by ConnorAtherton** [comment]
Okay. Your going to have to modify the source a little for this. Go to `source / _includes / article.html`.

On line 21 paste in this code

```
<div class="entry-content">{{ content | excerpt }}</div>
    {% capture excerpted %}{{ content | has_excerpt }}{% endcapture %}
    {% if excerpted == 'true' %}
      <footer>
        <a rel="full-article" href="{{ root_url }}{{ post.url }}">{{ site.excerpt_link }}</a>
      </footer>
    {% endif %}
```

That should do it! Oh and make sure you put `<!-- more -->` in the actual post for it to display the excerpt.

**Comment by aritzportuondo** [comment]
Works well! Thank you!

**Comment by aritzportuondo** [comment]
Sorry, but there is a mistake.

Now the code say this:



{% else %}

<div class="entry-content">{{ content | excerpt }}</div>

```
{% capture excerpted %}{{ content | has_excerpt }}{% endcapture %}
{% if excerpted == 'true' %}
  <footer>
    <a rel="full-article" href="{{ root_url }}{{ post.url }}">{{ site.excerpt_link }}</a>
  </footer>
{% endif %}
```

<div class="entry-content">{{ content }}</div>

{% endif %}

And the result is this:

![captura de pantalla 2013-11-21 a la s 13 48 00](https://f.cloud.github.com/assets/6000495/1591691/3d3e5e52-52ab-11e3-938a-25e6ca565eca.png)

**Comment by ConnorAtherton** [comment]
No problem.

**Comment by ConnorAtherton** [comment]
Can you please post your full `article.html`

**Comment by aritzportuondo** [comment]
Sorry Connor. The mistake was mine. Thanks for your help!

**Comment by ConnorAtherton** [comment]
Glad we got it sorted. Enjoy the theme. If you are using it for your own blog please could you post the link in the [wiki](https://github.com/ConnorAtherton/OctoPanel/wiki/All-sites-using-this-theme).
