### ISSUE TITLE
Distance

### ISSUE THREAD

**Issue by aritzportuondo** [ConnorAtherton/OctoPanel#6]
Hi Connor,

I want to know how can I reduce the distance from the date to the up of the doc. Now I think there is a lot of space and I want to reduce it.

![captura de pantalla 2013-11-21 a la s 19 03 17](https://f.cloud.github.com/assets/6000495/1594237/6aa168a4-52d7-11e3-86dd-f218d7f709b6.png)

Thanks!

**Comment by aritzportuondo** [comment]
Do you know what can I do?

**Comment by ConnorAtherton** [comment]
Go to `sass/base/_layout.scss` on line 124 you can modify the padding amount.

**Comment by aritzportuondo** [comment]
Worked well. Thanks.
