### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by aritzportuondo** [ConnorAtherton/OctoPanel#7]
Dear friend,

I'm using links on my blog and the problem is that they are not underlined nor changed the color. So, nobody can discern between a normal text and a linked one. ¿How can I change that?

**Comment by ConnorAtherton** [comment]
Are you sure you've wrote the links properly? Or have you added any custom styles because the theme does include styling for link interactions.

**Comment by aritzportuondo** [comment]
You can check it by yourself on this URL: http://www.puntodeancla.es/blog/23/11/2013/inauguracion-del-blog/

What I write when I want to make a link is:

![image](https://f.cloud.github.com/assets/6000495/1609187/300de9ba-5534-11e3-847a-4190374f8a74.png)

100% Markdown compatible.

**Comment by ConnorAtherton** [comment]
That should fix it.

**Comment by aritzportuondo** [comment]
That only fixed no-article links:

![links](https://f.cloud.github.com/assets/6000495/1611374/fbacf6cc-55a9-11e3-9358-5a9ae9d09bfb.jpg)

**Comment by aritzportuondo** [comment]
Updated: Only works when I go to "Read more" on each article, or when I click on article title to show all the text. It doesn't work in the main page where all posts are shown.

**Comment by ConnorAtherton** [comment]
Thanks for including a picture of what was happening, it made it easier to fix. I've tested it on my computer and now links should show up for excerpts on the home page. Let me know if it works for you.

**Comment by aritzportuondo** [comment]
Now works well. Thanks!
